/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/goals': typeof AppGoalsRoute
  '/memory': typeof AppMemoryRoute
  '/profile': typeof AppProfileRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/goals': typeof AppGoalsRoute
  '/memory': typeof AppMemoryRoute
  '/profile': typeof AppProfileRoute
  '/reminders': typeof AppRemindersRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/goals'
    | '/memory'
    | '/profile'
    | '/reminders'
    | '/settings'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/goals'
    | '/memory'
    | '/profile'
    | '/reminders'
    | '/settings'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/goals'
    | '/_app/memory'
    | '/_app/profile'
    | '/_app/reminders'
    | '/_app/settings'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppGoalsRoute: typeof AppGoalsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGoalsRoute: AppGoalsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
